//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grotto_Information_2022_WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ashleigh")]
        public string giFTPUsername {
            get {
                return ((string)(this["giFTPUsername"]));
            }
            set {
                this["giFTPUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jadzia1984!")]
        public string giFTPPassword {
            get {
                return ((string)(this["giFTPPassword"]));
            }
            set {
                this["giFTPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server")]
        public string giFTPHost {
            get {
                return ((string)(this["giFTPHost"]));
            }
            set {
                this["giFTPHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int giFTPPort {
            get {
                return ((int)(this["giFTPPort"]));
            }
            set {
                this["giFTPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giFTPAdult {
            get {
                return ((string)(this["giFTPAdult"]));
            }
            set {
                this["giFTPAdult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giFTPChild {
            get {
                return ((string)(this["giFTPChild"]));
            }
            set {
                this["giFTPChild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/x22")]
        public string giFTPFolder {
            get {
                return ((string)(this["giFTPFolder"]));
            }
            set {
                this["giFTPFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giFTPFamily {
            get {
                return ((string)(this["giFTPFamily"]));
            }
            set {
                this["giFTPFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int giGrottoCount {
            get {
                return ((int)(this["giGrottoCount"]));
            }
            set {
                this["giGrottoCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int giGrottoNumber {
            get {
                return ((int)(this["giGrottoNumber"]));
            }
            set {
                this["giGrottoNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Santa")]
        public string giSantaActor {
            get {
                return ((string)(this["giSantaActor"]));
            }
            set {
                this["giSantaActor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elf Actor")]
        public string giElfActor {
            get {
                return ((string)(this["giElfActor"]));
            }
            set {
                this["giElfActor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elf Name")]
        public string giElfName {
            get {
                return ((string)(this["giElfName"]));
            }
            set {
                this["giElfName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grotto Name")]
        public string giGrottoName {
            get {
                return ((string)(this["giGrottoName"]));
            }
            set {
                this["giGrottoName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int giTimerFamily {
            get {
                return ((int)(this["giTimerFamily"]));
            }
            set {
                this["giTimerFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int giTimerOverride {
            get {
                return ((int)(this["giTimerOverride"]));
            }
            set {
                this["giTimerOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string giPassword {
            get {
                return ((string)(this["giPassword"]));
            }
            set {
                this["giPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giBackupLocation {
            get {
                return ((string)(this["giBackupLocation"]));
            }
            set {
                this["giBackupLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giPicsDownloaded {
            get {
                return ((string)(this["giPicsDownloaded"]));
            }
            set {
                this["giPicsDownloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giPicsSanta {
            get {
                return ((string)(this["giPicsSanta"]));
            }
            set {
                this["giPicsSanta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/X22/GreenScreen")]
        public string giPicsGreenscreen {
            get {
                return ((string)(this["giPicsGreenscreen"]));
            }
            set {
                this["giPicsGreenscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giGrottoControllerLoc {
            get {
                return ((string)(this["giGrottoControllerLoc"]));
            }
            set {
                this["giGrottoControllerLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giGoogleAPI {
            get {
                return ((string)(this["giGoogleAPI"]));
            }
            set {
                this["giGoogleAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giSaveLocal {
            get {
                return ((string)(this["giSaveLocal"]));
            }
            set {
                this["giSaveLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giSaveServer {
            get {
                return ((string)(this["giSaveServer"]));
            }
            set {
                this["giSaveServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giMonitor {
            get {
                return ((string)(this["giMonitor"]));
            }
            set {
                this["giMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int giMainMonitor {
            get {
                return ((int)(this["giMainMonitor"]));
            }
            set {
                this["giMainMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int giSecondMonitor {
            get {
                return ((int)(this["giSecondMonitor"]));
            }
            set {
                this["giSecondMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giUnique {
            get {
                return ((string)(this["giUnique"]));
            }
            set {
                this["giUnique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giSavedXmas {
            get {
                return ((string)(this["giSavedXmas"]));
            }
            set {
                this["giSavedXmas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP")]
        public string giGSsetting {
            get {
                return ((string)(this["giGSsetting"]));
            }
            set {
                this["giGSsetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string giFTPSaved {
            get {
                return ((string)(this["giFTPSaved"]));
            }
            set {
                this["giFTPSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int giNameTimer {
            get {
                return ((int)(this["giNameTimer"]));
            }
            set {
                this["giNameTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int giMapSpeed {
            get {
                return ((int)(this["giMapSpeed"]));
            }
            set {
                this["giMapSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int giPhotoInterval {
            get {
                return ((int)(this["giPhotoInterval"]));
            }
            set {
                this["giPhotoInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int giDisplayInterval {
            get {
                return ((int)(this["giDisplayInterval"]));
            }
            set {
                this["giDisplayInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gibackup {
            get {
                return ((string)(this["gibackup"]));
            }
            set {
                this["gibackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",,,,,,,,,")]
        public string giBackupLocations {
            get {
                return ((string)(this["giBackupLocations"]));
            }
            set {
                this["giBackupLocations"] = value;
            }
        }
    }
}
